### PR TITLE
Update minimap-autohide.less

### PR DESCRIPTION
**Pull request by saidmoya12**
When atom-text-editor-minimap:hover is trigger keep visible if hover minimap.scrolling
Employ script instance of style.

Attachs some styles to improve left and right minimap position

### CODE REVIEW

**Comment by jayk** [comment]
Hi saidmoya12,

This looks pretty good.  I've got another request that I want to fit in.  I'll work on getting this merged in and released here shortly.  Thanks for the contribution!

Jay

**Comment by liuchangxing** [comment]
He doesn't work.

**Comment by liuchangxing** [comment]
Please help me

**Comment by jayk** [comment]
This module is deprecated... Please use [@ansballard's excellent replacement](https://github.com/ansballard/minimap-autohider) instead.

**Pull request closed without merging**
