### PR TITLE
Corresponding to atom version 1.13.0 or later

### PR DESCRIPTION
**Pull request by ghost**
Fix for Deprecated call and Deprecated selector

### CODE REVIEW

**Comment by davisonio** [comment]
@jayk

**Comment by ansballard** [comment]
There hasn't been any activity on this repo from the author for quite a while, so I published a fork with the above deprecations fixed at `apm install minimap-autohider`. Hopefully this gets merged in at some point, but if you'd like a holdover without deprecation warnings, mine is stable =)

**Comment by ghost** [comment]
Thank you very mach @ansballard !

**Comment by jayk** [comment]
@ansballard - Are you interested in taking over this plugin?  I haven't been using atom for some time and sadly I neglected this repo.  If so, I'll post a deprecation warning and point people at your repo / plugin instead...

**Comment by ansballard** [comment]
Sure, I'm happy to take over. I use atom pretty consistently so it should stay on my radar for the foreseeable future. Thanks for hopping back in, by the way!

**Pull request merged**
